[package]
name = "wt_ext_cli"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = "thin"
debug = true

[dependencies]
clap = {version = "4.1.9", features = ["derive"]}
indicatif = "0.17.3"
wt_blk = {path = "../wt_blk"}

tracing = "^0.1.37"
tracing-subscriber = {version  = "^0.3.16", features = ["tracing-log", "env-filter", "fmt", "std"]}